### ISSUE TITLE
Error when start miner.

### ISSUE THREAD

**Issue by ICOBOXER** [valiant1x/intense-pool#1]
My Pool is http://intense.miningpools.us I was able to launch the pool It is running fine. However when I start my miner it does not start and I get this error in the pool:

Error: Failed to parse block
    at Object.BlockTemplate.nextBlob (/home/cmilian/pool/lib/pool.js:129:23)
    at Object.Miner.getJob (/home/cmilian/pool/lib/pool.js:308:41)
    at handleMinerMethod (/home/cmilian/pool/lib/pool.js:510:28)
    at handleMessage (/home/cmilian/pool/lib/pool.js:645:13)
    at Socket.socket.on.on.on.pushMessage (/home/cmilian/pool/lib/pool.js:699:25)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)

2017-11-08 02:02:06 [master] Pool fork 1 died, spawning replacement worker...

Any ideas?

**Comment by isbkch** [comment]
What distro and npm version are you using ?

**Comment by panthar1** [comment]
Same problem,  NPM 1.2.15 and Ubuntu
