### ISSUE TITLE
How to deploy intense-pool ?

### ISSUE THREAD

**Issue by cryptogrot** [valiant1x/intense-pool#5]
Hi,

Could you please give us more information about how you deployed `intense-pool` ?
Like the versions of the following components:

- Linux distribution and version
- GCC version
- NodeJS version
- NPM version

Because when I try to deploy on `Ubuntu 16.04.3` with `GCC 7.2` and `NodeJS 9.3.0` I got this error message:

```gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.13.0-19-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/intense-pool/node_modules/multi-hashing
gyp ERR! node -v v4.8.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.13.0-19-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/intense-pool/npm-debug.log
```

Thanks for your help.

**Comment by valiant1x** [comment]
node 0.10 or 0.12 is required unfortunately. i used gcc 4.8.4 and ubuntu 14.04.

**Comment by cryptogrot** [comment]
@valiant1x Thanks.
